# Generated by Django 4.2.3 on 2023-07-31 15:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import drone.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[+/%*]', inverse_match=True)])),
                ('weight', models.FloatField()),
                ('code', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]*$', message='Only uppercase letters, numbers and underscore allowed')])),
                ('image', models.ImageField(blank=True, null=True, upload_to=drone.models.upload_to)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='drone_medic_name_3f4b33_idx')],
            },
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('model', models.CharField(choices=[('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'), ('Cruiserweight', 'Cruiserweight'), ('Heavyweight', 'Heavyweight')], default='Lightweight', max_length=13)),
                ('weigth_limit', models.FloatField(help_text='Value in grams', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('battery_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('state', models.CharField(choices=[('Idle', 'Idel'), ('Loading', 'Loading'), ('Loaded', 'Loaded'), ('Delivering', 'Delivering'), ('Returning', 'Returning')], default='Idle', max_length=10)),
                ('medication', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medication_on_drone', to='drone.medication')),
            ],
            options={
                'indexes': [models.Index(fields=['serial_number'], name='drone_drone_serial__93e319_idx')],
            },
        ),
    ]
