# Generated by Django 4.2.3 on 2023-08-01 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medication_on_drone', to='drone.medication'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='state',
            field=models.CharField(choices=[('Idle', 'Idle'), ('Loading', 'Loading'), ('Loaded', 'Loaded'), ('Delivering', 'Delivering'), ('Returning', 'Returning')], default='Idle', max_length=10),
        ),
    ]
