# Generated by Django 4.2.3 on 2023-08-01 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0002_alter_drone_medication_alter_drone_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='serial_number',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9]', message='Insert only numbers')]),
        ),
    ]
