# Generated by Django 4.2.3 on 2023-08-02 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0004_alter_drone_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='medication',
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drone.drone')),
                ('medications', models.ManyToManyField(to='drone.medication')),
            ],
        ),
    ]
